### ISSUE TITLE
Using earlier versons of action always uses latest version of container

### ISSUE THREAD

**Issue by gardar** [gofrolist/molecule-action#140]
When attempting to use older versions of the action, (either to get a version that has older versions of ansible/molecule or to pin the workflow to a known working version of the action), it always results in the latest version of the container.

Being able to pin a specific verios of the action/container would avoid unexpected issues such as: #138 

It would be good if the versions of the action would either match the corresponding container version or if it would be possible to overwrite the container version used via a env variable for example.

Perhaps something like this could work?

```yaml
runs:
  using: docker
  image: docker://gofrolist/molecule:v${MOLECULE_CONTAINER_VERSION}
  env:
    ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"
    ANSIBLE_FORCE_COLOR: "1"
    MOLECULE_CONTAINER_VERSION: "2"
```
